alerting:
  providers:
    - name: github-issues
      type: github
      token: "<github-token>" # Ini akan diganti otomatis oleh Pipeline
      repository: "Raditt10/gatus-leantime-app" # Sesuaikan dengan USERNAME/REPO kamu
      overrides:
        - description: "Service is down!"
          send-on-resolved: true
          failure-threshold: 3
          success-threshold: 5

endpoints:
  - name: Leantime Homepage
    group: core
    url: "<leantime-url>" # Ini akan diganti otomatis oleh Pipeline
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"

  - name: Gatus Monitoring
    group: core
    url: "<gatus-url>" # Ini akan diganti otomatis oleh Pipeline
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"